### ISSUE TITLE
Multiple definitions of xs⊆xs++ys.

### ISSUE THREAD

**Issue by tuncbkose** [wenkokke/schmitty#27]
https://github.com/agda/agda-stdlib/commit/c49854d2372ca54ff66d1a60808e1983392b7e1a#diff-e0f22a07a1e767e68cb3581868064af185b9557ffbf50917c8668c9ad61b1f14 leads to the error
 ```
 ~/work/schmitty-master/src/Data/List/Relation/Binary/Subset/Propositional/ExtraProperties.agda:22,1-10
Multiple definitions of xs⊆xs++ys. Previous definition at
~/work/agda-stdlib-experimental/src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda:139,1-10
when scope checking the declaration
  xs⊆xs++ys : xs ⊆ xs ++ ys
```
at least on the current state of the experimental standard library.

Also, schmitty's readme says the standard library should be at least https://github.com/agda/agda-stdlib/commit/da286d0e2c767074faa218cbca53aaf5a1b8fc7f but the link https://github.com/agda/agda-stdlib/pull/1285/commits/9c56155ffdc1930b6c33caa38ef384ab8cc2dba1 is for an earlier pull request. In both cases, I get the error
```
~/work/agda-stdlib/src/Reflection/Term.agda:392,20-26
Too few arguments to constructor absurd, expected 1 more explicit
argument
when checking that the pattern absurd has type Pattern
```
I am not sure how to proceed in trying to get the tests to run. I appreciate any advice!

**Comment by MatthewDaggitt** [comment]
Hi @tuncbkose, apologies the fact that we're waiting for Agda 2.6.2 to release means that stability is somewhat of a moving target at the moment. Once it releases in April, this library will be on a much steadier footing.

I've just pushed a commit that fixes the problems with the latest experimental version of the standard library https://github.com/agda/agda-stdlib/commit/d66a21f1242b893bb6ead4f6ef6da0a5490924c2.

I think the dev version of Agda has also changed recently, hence the second error. The tests all pass for me on  https://github.com/agda/agda/commit/60564a4

Hope that helps!

**Comment by tuncbkose** [comment]
Thank you @MatthewDaggitt! I have grabbed the latest versions of the experimental stdlib and schmitty and now most things work. For running `Test_Scripts_Z3_RealsAsFloat.agda`, I still get the error
```
Failed to parse output:

sat
(
  (define-fun x_0 () Real
    4.0)
  (define-fun y_1 () Real
    2.0)
)

when running script:

z3 -smt2 -in -v:0
(declare-const x_0 Real)
(declare-const y_1 Real)
(assert (= y_1 (/ x_0 2.0)))
(assert (> y_1 1.0))
(assert (> x_0 1.0))
(check-sat)
(get-model)
when checking that the expression unquote (z3 script) has type
Outputs (MODEL (REAL ∷ REAL ∷ []) ∷ [])
```
I imagined this might be related to agdarsec, so I tried it with both https://github.com/gallais/agdarsec/commit/b26230ab714cddc23f1fe242d8a80abbf3b43d4f and v0.4.0 release and got the same error. I just wanted to let it be known in case it is a real problem and not just me missing anything.

**Comment by MatthewDaggitt** [comment]
That test passes for me on https://github.com/gallais/agdarsec/commit/b26230ab714cddc23f1fe242d8a80abbf3b43d4f ? I don't think we've got around to upgrading to v0.4.0 yet...
